services:
  - type: web
    name: dteworks-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
   envVars:
  - key: NODE_ENV
    value: production
  - key: IS_DOCKER
    value: 'true'
    autoDeploy: true
